// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/http/list_posts/deps.go
//
// Generated by this command:
//
//	mockgen -source=./internal/transport/http/list_posts/deps.go -destination=./internal/transport/http/list_posts/deps_mock.go -package=list_posts
//

// Package list_posts is a generated GoMock package.
package list_posts

import (
	context "context"
	list_posts "reddit-clone/internal/application/query/list_posts"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockListPostsQueryHandler is a mock of ListPostsQueryHandler interface.
type MockListPostsQueryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockListPostsQueryHandlerMockRecorder
	isgomock struct{}
}

// MockListPostsQueryHandlerMockRecorder is the mock recorder for MockListPostsQueryHandler.
type MockListPostsQueryHandlerMockRecorder struct {
	mock *MockListPostsQueryHandler
}

// NewMockListPostsQueryHandler creates a new mock instance.
func NewMockListPostsQueryHandler(ctrl *gomock.Controller) *MockListPostsQueryHandler {
	mock := &MockListPostsQueryHandler{ctrl: ctrl}
	mock.recorder = &MockListPostsQueryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListPostsQueryHandler) EXPECT() *MockListPostsQueryHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockListPostsQueryHandler) Handle(ctx context.Context) (list_posts.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx)
	ret0, _ := ret[0].(list_posts.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockListPostsQueryHandlerMockRecorder) Handle(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockListPostsQueryHandler)(nil).Handle), ctx)
}
