// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/http/get_post/deps.go
//
// Generated by this command:
//
//	mockgen -source=./internal/transport/http/get_post/deps.go -destination=./internal/transport/http/get_post/deps_mock.go -package=get_post
//

// Package get_post is a generated GoMock package.
package get_post

import (
	context "context"
	get_post "reddit-clone/internal/application/query/get_post"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetPostQueryHandler is a mock of GetPostQueryHandler interface.
type MockGetPostQueryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGetPostQueryHandlerMockRecorder
	isgomock struct{}
}

// MockGetPostQueryHandlerMockRecorder is the mock recorder for MockGetPostQueryHandler.
type MockGetPostQueryHandlerMockRecorder struct {
	mock *MockGetPostQueryHandler
}

// NewMockGetPostQueryHandler creates a new mock instance.
func NewMockGetPostQueryHandler(ctrl *gomock.Controller) *MockGetPostQueryHandler {
	mock := &MockGetPostQueryHandler{ctrl: ctrl}
	mock.recorder = &MockGetPostQueryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPostQueryHandler) EXPECT() *MockGetPostQueryHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockGetPostQueryHandler) Handle(ctx context.Context, query get_post.Query) (get_post.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, query)
	ret0, _ := ret[0].(get_post.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockGetPostQueryHandlerMockRecorder) Handle(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockGetPostQueryHandler)(nil).Handle), ctx, query)
}
