// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/http/delete_post/deps.go
//
// Generated by this command:
//
//	mockgen -source=./internal/transport/http/delete_post/deps.go -destination=./internal/transport/http/delete_post/deps_mock.go -package=delete_post
//

// Package delete_post is a generated GoMock package.
package delete_post

import (
	context "context"
	delete_post "reddit-clone/internal/application/command/delete_post"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeletePostCommandHandler is a mock of DeletePostCommandHandler interface.
type MockDeletePostCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDeletePostCommandHandlerMockRecorder
	isgomock struct{}
}

// MockDeletePostCommandHandlerMockRecorder is the mock recorder for MockDeletePostCommandHandler.
type MockDeletePostCommandHandlerMockRecorder struct {
	mock *MockDeletePostCommandHandler
}

// NewMockDeletePostCommandHandler creates a new mock instance.
func NewMockDeletePostCommandHandler(ctrl *gomock.Controller) *MockDeletePostCommandHandler {
	mock := &MockDeletePostCommandHandler{ctrl: ctrl}
	mock.recorder = &MockDeletePostCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeletePostCommandHandler) EXPECT() *MockDeletePostCommandHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockDeletePostCommandHandler) Handle(ctx context.Context, cmd delete_post.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockDeletePostCommandHandlerMockRecorder) Handle(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockDeletePostCommandHandler)(nil).Handle), ctx, cmd)
}
