// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/http/create_post/deps.go
//
// Generated by this command:
//
//	mockgen -source=./internal/transport/http/create_post/deps.go -destination=./internal/transport/http/create_post/deps_mock.go -package=create_post
//

// Package create_post is a generated GoMock package.
package create_post

import (
	context "context"
	create_post "reddit-clone/internal/application/command/create_post"
	domain "reddit-clone/internal/domain/post"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateCommand is a mock of CreateCommand interface.
type MockCreateCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCreateCommandMockRecorder
	isgomock struct{}
}

// MockCreateCommandMockRecorder is the mock recorder for MockCreateCommand.
type MockCreateCommandMockRecorder struct {
	mock *MockCreateCommand
}

// NewMockCreateCommand creates a new mock instance.
func NewMockCreateCommand(ctrl *gomock.Controller) *MockCreateCommand {
	mock := &MockCreateCommand{ctrl: ctrl}
	mock.recorder = &MockCreateCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateCommand) EXPECT() *MockCreateCommandMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockCreateCommand) Handle(ctx context.Context, cmd create_post.Command) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, cmd)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCreateCommandMockRecorder) Handle(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCreateCommand)(nil).Handle), ctx, cmd)
}
