// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/http/create_post/deps.go
//
// Generated by this command:
//
//	mockgen -source=./internal/transport/http/create_post/deps.go -destination=./internal/transport/http/create_post/deps_mock.go -package=create_post
//

// Package create_post is a generated GoMock package.
package create_post

import (
	context "context"
	create_post "reddit-clone/internal/application/command/create_post"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreatePostCommandHandler is a mock of CreatePostCommandHandler interface.
type MockCreatePostCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePostCommandHandlerMockRecorder
	isgomock struct{}
}

// MockCreatePostCommandHandlerMockRecorder is the mock recorder for MockCreatePostCommandHandler.
type MockCreatePostCommandHandlerMockRecorder struct {
	mock *MockCreatePostCommandHandler
}

// NewMockCreatePostCommandHandler creates a new mock instance.
func NewMockCreatePostCommandHandler(ctrl *gomock.Controller) *MockCreatePostCommandHandler {
	mock := &MockCreatePostCommandHandler{ctrl: ctrl}
	mock.recorder = &MockCreatePostCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePostCommandHandler) EXPECT() *MockCreatePostCommandHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockCreatePostCommandHandler) Handle(ctx context.Context, cmd create_post.Command) (create_post.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, cmd)
	ret0, _ := ret[0].(create_post.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCreatePostCommandHandlerMockRecorder) Handle(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCreatePostCommandHandler)(nil).Handle), ctx, cmd)
}
