// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/transport/http/update_post/deps.go
//
// Generated by this command:
//
//	mockgen -source=./internal/transport/http/update_post/deps.go -destination=./internal/transport/http/update_post/deps_mock.go -package=update_post
//

// Package update_post is a generated GoMock package.
package update_post

import (
	context "context"
	update_post "reddit-clone/internal/application/command/update_post"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdatePostCommandHandler is a mock of UpdatePostCommandHandler interface.
type MockUpdatePostCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatePostCommandHandlerMockRecorder
	isgomock struct{}
}

// MockUpdatePostCommandHandlerMockRecorder is the mock recorder for MockUpdatePostCommandHandler.
type MockUpdatePostCommandHandlerMockRecorder struct {
	mock *MockUpdatePostCommandHandler
}

// NewMockUpdatePostCommandHandler creates a new mock instance.
func NewMockUpdatePostCommandHandler(ctrl *gomock.Controller) *MockUpdatePostCommandHandler {
	mock := &MockUpdatePostCommandHandler{ctrl: ctrl}
	mock.recorder = &MockUpdatePostCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatePostCommandHandler) EXPECT() *MockUpdatePostCommandHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockUpdatePostCommandHandler) Handle(ctx context.Context, cmd update_post.Command) (update_post.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, cmd)
	ret0, _ := ret[0].(update_post.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockUpdatePostCommandHandlerMockRecorder) Handle(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockUpdatePostCommandHandler)(nil).Handle), ctx, cmd)
}
